# Generated by Django 4.2.13 on 2024-07-04 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0009_delete_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(editable=False, max_length=32)),
                ('donation_amount', models.DecimalField(decimal_places=2, help_text='The donation made by the user.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='Please ensure min donation is greater than €0.01')])),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_donation', to='charity.charity')),
                ('donation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
