# Generated by Django 4.2.13 on 2024-06-29 20:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('entry_donation', models.DecimalField(decimal_places=2, help_text='The minimum donation required to enter the charity community.', max_digits=5)),
                ('category', models.CharField(choices=[('Animal', 'Animal Welfare'), ('Conservation', 'Conservation'), ('Children', 'Children & Youth'), ('Homelessness', 'Homelessness'), ('Disaster', 'Disaster Relief'), ('Education', 'Education'), ('Environment', 'Environment'), ('Medical', 'Medical Research'), ('Sustainability', 'Sustainable Development'), ('Humanitarian', 'Humanitarian Aid')], max_length=25)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
