# Generated by Django 4.2.13 on 2024-06-29 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='entry_donation',
            field=models.DecimalField(decimal_places=2, help_text='The min donation required to enter the charity community.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='Ensure min donation is greater than €0.01')]),
        ),
    ]
