# Generated by Django 4.2.13 on 2024-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_charity_entry_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='category',
            field=models.CharField(choices=[('Animal', 'Animal Welfare'), ('Children', 'Children & Youth'), ('Conservation', 'Conservation'), ('Disaster', 'Disaster Relief'), ('Education', 'Education'), ('Environment', 'Environment'), ('Homelessness', 'Homelessness'), ('Humanitarian', 'Humanitarian Aid'), ('Medical', 'Medical Research'), ('Sustainability', 'Sustainable Development'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
