# Generated by Django 4.2.13 on 2024-06-29 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0003_alter_charity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='entry_donation',
            field=models.DecimalField(decimal_places=2, help_text='The min donation required to enter the charity community.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='Please ensure min donation is greater than €0.01')]),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The donation made by the user.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='Please ensure min donation is greater than €0.01')])),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_donation', to='charity.charity')),
                ('donatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_donatee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
