# Generated by Django 4.2.13 on 2024-06-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charity_entry_donation_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date']},
        ),
    ]
