# Generated by Django 4.2.13 on 2024-06-29 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0005_alter_donation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['-community_size']},
        ),
        migrations.AddField(
            model_name='charity',
            name='community_size',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='charity',
            name='donated_to_by',
            field=models.ManyToManyField(blank=True, editable=False, related_name='donated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
