# Generated by Django 4.2.13 on 2024-07-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
