# Generated by Django 4.2.13 on 2024-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
